# General
title: Chorale Status
languageCode: en-US
baseURL: /
permalinks:
  incidents: /incidents/:year/:month/:day/:slug/
params:
  # Extra customization
  logo: /logo.png
  description: We continuously monitor the status of our services and if there are any interruptions, a note will be posted here. For the best experience, use a modern browser like Chrome.
  # Current state
  announcement: Everything looks fine, but if you see something wrong, give us a shout by using the chat box in the bottom right corner.
