# General
title: Chorale Status
languageCode: en-US
baseURL: /
permalinks:
  incidents: /incidents/:year/:month/:day/:slug/
params:
  # Extra customization
  logo: https://www.choraleapp.com/logo.png
  description: We continuously monitor the status of our services and if there are any interruptions, a note will be posted here. Latency measurements work only on modern browsers and may not be 100% accurate. A ping below 1000ms is usually acceptable.
  # Current state
  announcement: Status page has a hiccup with HTTPS, looking into it.
