# This is the main configuration file for Netlify CMS.
# Netlify CMS is used as the admin panel for cState.
#
# While some settings here can be kept as is, you may
# want to change some for a more customized solution.
#
# You can look at what each option does and how to
# toggle between them on the Netlify CMS repo docs:
#
# https://github.com/netlify/netlify-cms/blob/master/docs/quick-start.md

backend:
  name: git-gateway
media_folder: "static/img"
public_folder: "/img"
  # Do not change this!
  collections:
    # Used in routes, e.g., /admin/collections/blog
  - name: "issue"
    # Used in the UI
    label: "Issues"
    # The path to the folder where the documents are stored
    folder: "content/issues"
    # Allow users to create new documents in this collection
    create: true
    # Filename template, e.g., YYYY-MM-DD-title.md
    slug: "{{slug}}.md"
    # The fields for each document, usually in front matter
    fields:
      - {label: "Section", name: "Section", widget: "hidden", default: "issue"}

      - {label: "What is this issue about?", name: "Title", widget: "string"}
      - {label: "When did this issue begin?", name: "Date", widget: "datetime"}

      - {label: "Has it now been fully resolved?", name: "Resolved", widget: "boolean"}
      - {label: "When did downtime end (if it did)?", name: "ResolvedWhen", widget: "date"}

      - {label: "What is the severity?", name: "Severity", widget: "string", options: ['disrupted', 'down', 'notice']}
      - {label: "What is affected? Example: ['API', 'Media Proxy']", name: "Affected", widget: "string"}
      - {label: "Write any relevant notes here.", name: "body", widget: "markdown"}
