# This is the main configuration file for Netlify CMS.
# Netlify CMS is used as the admin panel for cState.
#
# While some settings here can be kept as is, you may
# want to change some for a more customized solution.
#
# You can look at what each option does and how to
# toggle between them on the Netlify CMS repo docs:
#
# https://github.com/netlify/netlify-cms/blob/master/docs/quick-start.md

backend:
  name: git-gateway
media_folder: "static/img"
public_folder: "/img"
display_url: /
# Do not change this!
collections:
    # Used in routes, e.g., /admin/collections/blog
  - name: "issue"
    # Used in the UI
    label: "Incident"
    # The path to the folder where the documents are stored
    folder: "content/issues"
    # Allow users to create new documents in this collection
    create: true
    # Filename template, e.g., YYYY-MM-DD-title.md
    slug: "{{slug}}"
    # The fields for each document, usually in front matter
    fields:
      # Hidden
      - {label: "Mark as incident", name: "Section", widget: "hidden", default: "issue"}
      # Very basic
      - {label: "Title", name: "Title", widget: "string"}
      - {label: "Start date & time", name: "Date", widget: "datetime"}
      - {label: "Mark as resolved", name: "Resolved", widget: "boolean"}
      - {label: "End date & time", name: "ResolvedWhen", widget: "datetime", required: false}
      - label: "Severity"
        name: "Severity"
        widget: "select"
        options:
          - { label: "High (Down)", value: "down" }
          - { label: "Medium (Disrupted)", value: "disrupted" }
          - { label: "Low (Maintenance)", value: "notice" }
      - label: "Affected systems (use exact name)"
        name: "Affected"
        widget: "list"
        required: false
      - {label: "Sequence of events", name: "body", widget: "markdown", default: "We are investigating a potential issue that might affect the uptime of one our of services."}
